name: laundri
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_input: ^0.1.3
  d_method: ^0.2.6
  d_view: ^0.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.10
  google_fonts: 6.1.0
  http: ^1.1.0
  intl: ^0.19.0
  intrinsic_dimension: ^0.3.1
  rating_bar_flutter: ^1.0.2
  riverpod: ^2.5.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
